"""empty message

Revision ID: eba1ad87270c
Revises: 0d15650f983f
Create Date: 2019-09-22 15:31:01.198076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba1ad87270c'
down_revision = '0d15650f983f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parcel_destination_key', 'parcel', type_='unique')
    op.drop_constraint('parcel_pick_up_location_key', 'parcel', type_='unique')
    op.drop_constraint('parcel_status_key', 'parcel', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('parcel_status_key', 'parcel', ['status'])
    op.create_unique_constraint('parcel_pick_up_location_key', 'parcel', ['pick_up_location'])
    op.create_unique_constraint('parcel_destination_key', 'parcel', ['destination'])
    # ### end Alembic commands ###
